### ISSUE TITLE
[Android] Call never ends when killing app (Critical)

### ISSUE THREAD

**Issue by stephanoparaskeva** [QuickBlox/quickblox-react-native-sdk#30]
With Android, during a call, the call will not end if you terminate/kill the app.
This is because the JS Bridge is never closed even if you close app.

**Comment by BertoGz** [comment]
i'm also experiencing this as well...

**Comment by BertoGz** [comment]
its fixable if you simply add a component unmount function to call the Hangup method ( this will only work on android )

**Comment by stephanoparaskeva** [comment]
>  its fixable if you simply add a component unmount function to call the Hangup method ( this will only work on android )

Really that's just a workaround in the JS, the bug will still exist. The bug is a problem in the Native module where one of the tasks or processes doesn't  end or finish correctly.

Here is a response where a WebRTC expert explains this 

https://github.com/react-native-webrtc/react-native-webrtc/issues/935#issuecomment-780596085

**Comment by BertoGz** [comment]
hmm i'm not sure where he mentioned that its a bug. he did mention there has to be a ongoing process. so i suppose if you didn't end the call session I supposed that task will continue.

**Comment by stephanoparaskeva** [comment]
@BertoGz 

That’s a sensible assumption.

Can I add you on LinkedIn by any chance?

We both seem to be working with the same library and have had the same
issue, it might be useful to discuss further things. In the future

**Comment by BertoGz** [comment]
sure!

**Comment by stephanoparaskeva** [comment]
Keeping this open as I have used ConnectyCube and they successfully close the bridge/app and tasks when app is terminated not sure why quickblox doesn't.

**Comment by ghost** [comment]
@stephanoparaskeva Hello,

This is Nikolay from QuickBlox support.

According to my check, the answer was provided in a ticket.

Please find the answer below:
This is the expected behavior as ReactNative SDK doesn't have a logic with start/stop/pause/close/open of the application and if you need to finish the call you should stop the service instead of the application termination. The work of the calling functionality continues even the application user tries to terminate, minimize or close the application. For example it helps to avoid the random closing of the application/ongoing call/ongoing action by the application user.

Once React Native SDK method "QB.webrtc.init()" is called (call is initiated) - Android foreground service starts to work. During the working of Android foreground service there is a default notification about the ongoing call in the notification status bar of the device.  Such workflow is a requirement made by Android for foreground services, URL: [https://developer.android.com/guide/components/foreground-services  ](https://developer.android.com/guide/components/foreground-services  )
If the application user wants to drop the call, he/she could tap the notification about the ongoing call in the notification status bar, the application will be opened and the application user has a possibility to finish the call. 

Please let me know if the issue can be closed.

**Comment by erennyuksell** [comment]
@stephanoparaskeva i have a same problem did you solve it? Listening to the destruction of the application and close the connection maybe solve problem. Which navigation library are you using?
