### ISSUE TITLE
Error: Can't load file from uriString when upload audio file Android

### ISSUE THREAD

**Issue by GARINED** [QuickBlox/quickblox-react-native-sdk#35]
Hi,

I hope someone can help me with my problem because I've been at it for 8 hours now and I can't find the solution.

So here I am creating a chat with voice messages with quickblox so I can record voice messages correctly which are stored locally on my device. I can upload them correctly to an ios device but as soon as I want to upload a voice from an android phone I get this error message: 
![terminal](https://user-images.githubusercontent.com/54508272/122533248-9f4c2d80-d021-11eb-86c3-458ac6acbcb4.png)

and this is my function:
![storm](https://user-images.githubusercontent.com/54508272/122467764-33cf7500-cfbb-11eb-8368-003f308e3d7a.png)

Thanks

**Comment by ghost** [comment]
Hello Garine,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant for you.

Make sure that you use the latest version of the QuickBlox React Native SDK:
https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.13-beta

Also, please check our clear React Native sample where uploading functionality is implemented correctly: https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/chat-sample

If the sample works as expected from your side, you can take it as an example for further integration of uploads into your applications/projects.
You may try comparing your custom code with the sample for a better understanding of how uploads work.
Our service supports all attachment types.
Can you please try to create a separate file with extension .m4a and try to upload it to the QuickBlox server?
Additionally, please provide us with full logs from your application.
It can be the issue with supporting Android .m4a file extension so you can try to save a voice message in another file format: [M4A File Extension - What is an .m4a file ](https://fileinfo.com/extension/m4a)

Please be notified that we don’t have voice messages functionality. Implementation of this custom logic is up to the customer side.

**Comment by poliahrameshkumar** [comment]
@GARINED Did you find solution for this Audio upload issue? I am also facing the same issue. If you had resolved it, Please let me know the solution.

**Comment by poliahrameshkumar** [comment]
@QB-nikolay-zolotarov Can you provide solution on this as we are struck in this issue for a week. If it doesn't work, then we need to go for other providers as we need voice message functionality. Please confirm. Image attachment and video attachments are working. This problem is with Audio and PDF files.

**Comment by ghost** [comment]
@poliahrameshkumar Hello, I have forwarded the request to our developers. Once there is any news, we will let you know.

**Comment by ghost** [comment]
@GARINED @poliahrameshkumar Please check the attached archive with a sample code with the possibility to send any files as chat message attachments. As we have checked, it works with .pdf, .mp3
[quickblox-react-native-chat-sample.zip](https://github.com/QuickBlox/quickblox-react-native-sdk/files/8040476/quickblox-react-native-chat-sample.zip)
.
