### ISSUE TITLE
Unable to run project with version 0.64

### ISSUE THREAD

**Issue by Rd1120** [QuickBlox/quickblox-react-native-sdk#37]

**Comment by ghost** [comment]
Hello 

This is Nikolay from QuickBlox support.

We released an update for our React Native Chat sample. Now it uses react-native 0.66.0.
Please use the latest code from the React Native chat sample repository.
Here is a link:

[https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/chat-sample](https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/chat-sample)

Please check it on your end and let me know if the issue is resolved.
