### ISSUE TITLE
Unable to compile project on version 0.64.And unable to merge project another project also.

### ISSUE THREAD

**Issue by rimmid** [QuickBlox/quickblox-react-native-sdk#38]
![Screenshot 2021-09-16 at 7 17 24 PM](https://user-images.githubusercontent.com/90849492/133625108-5cc825b7-3056-4e3a-be1f-b613c6bcd2b9.png)

**Comment by ghost** [comment]
Hello @rimmid 

This is Nikolay from QuickBlox support.

We released an update for our React Native Chat sample. Now it uses react-native 0.66.0.
Please use the latest code from the React Native chat sample repository.
Here is a link:

[https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/chat-sample](https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/chat-sample)

Please check it on your end and let me know if the issue is resolved.
