### ISSUE TITLE
how to attach gif in messages

### ISSUE THREAD

**Issue by bobananto24** [QuickBlox/quickblox-react-native-sdk#39]
```
QB.content
      .upload({ url, public: false }) // url contains the gif url
      .then(function (file) {
        console.log("Media sent :", file);
        const message = {
          attachments: [],
          dialogId: dialogId,
          body: msgBody,
          saveToHistory: true,
        };
        message.attachments.push({
          id: file.uid,
          type: file.contentType.includes("image") ? "image" : "file", 
        });
.catch(function (e) {
        console.log("media send error:", e);
      
      });
```
This is the code that I have used.

This is the error i got : 
media send error: Error: Request failed: not found (404)
    at Object.promiseMethodWrapper [as upload] (NativeModules.js:104)
    at Object.upload (index.js:1370)
    at onMediaSen (VM19 ConversationScreen.bundle:853)
    at onMediaSend$ (VM19 ConversationScreen.bundle:783)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tryCatch (runtime.js:63)
    at invoke (runtime.js:154)
    at runtime.js:164
Please give me your suggestions in this @dgem @Nitrino @SerhiiEngalychev @olegshestakov @nmacleitch

**Comment by ghost** [comment]
Hello Boban,

This is Nikolay from QuickBlox support.

It is allowed to upload any files using our SDK. Please let me know if you followed our documentation regarding the content module:
[https://docs.quickblox.com/docs/react-native-content](https://docs.quickblox.com/docs/react-native-content)

Also, you may check our React Native chat sample where you can upload .gif files:
[https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/chat-sample](https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/chat-sample)

Unfortunately, the sample seems to be not optimized for uploading .gif files and there could be some other errors. However, it can be useful anyway.

In order to investigate the issue, please provide me with:
1. Version of QuickBlox React Native SDK.
Please make sure that you use the latest version of the React Native SDK.
Here is a link to download: [https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta](https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.14-beta)
2. Platform where the issue is reproduced (Android, iOS, or both).
3. Version of the platform (e.g. Android 11, iOS 13).
4. React Native version.
5. Information from react-native info.
6. Information from npm list.
7. Please provide us with full REST + XMPP logs as an attachment in .txt format. 
You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/section/14-gathering-logs-guides)
