### ISSUE TITLE
Getting error on file attachments in message on iOS simulator

### ISSUE THREAD

**Issue by joytomchin** [QuickBlox/quickblox-react-native-sdk#48]
Code:

```
  const contentUploadParams = {
      url: inputFile.uri,
      public: false,
    };

  QB.content
        .upload(contentUploadParams)
        .then(function (file) {
          const message = {
            attachments: [],
            saveToHistory: true,
            ...msg,
          };
          console.warn('attachments ',  file.contentType);
        })
        .catch(function (e) {
          console.warn('SendMessageWithAttachment ', e);
          reject(e);
        });
```

url path:

```
'file:///Users/Joy/Library/Devices/823DCE40-17DF-4F45-B2F8-11F3E4BAEA54/data/Containers/Data/Application/512710B2-F744-4764-B825-13A7C5D65475/tmp/96DD7222-D8FA-4839-91A5-4FE8887AA247.jpg'
```

Error:

```
[Error: "content_type" is too short (minimum is 5 characters)
"content_type" is too long (maximum is 100 characters)
]
```

**Comment by ghost** [comment]
@joytomchin Hello,

This is Nikolay from QuickBlox support.

In order to investigate the issue, we need the following points:
1. Please specify the file size. You may also attach that file.
2. Please let us know if the issue can be reproduced on the latest version of the QuickBlox React Native SDK:
https://github.com/QuickBlox/quickblox-react-native-sdk/releases/tag/0.5.18-beta
3. Is this issue intermittent or permanent?
4. What are the steps to reproduce on our side?
5. Please provide us with more detailed information about the application logic and workflow you would like to achieve.
6. Did you get this issue in your code or on samples?
7. Please try reproducing the issue on our samples in order to understand if the issue is related to the client-side implementation or to the SDK.
Here is a link:
https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/chat-sample
8. Please provide us with full REST + XMPP logs as an attachment in .txt format. You can find out how to gather logs here: https://help.quickblox.com/article/368-how-can-i-enable-quickblox-logs
9. iOS version.
10. Device version (e.g. iPhone 12).
11. React Native version.
12. Information from react-native info.
13. Information from npm list.

**Comment by vikrampunchh** [comment]
The file size is less than 1 MB and using 0.5.18-beta version

I'm getting this error every time.

**Comment by joytomchin** [comment]
The file size is less than 1 MB and using 0.5.18-beta version

I'm getting this error every time.

**Comment by ghost** [comment]
@joytomchin Please provide me with the rest points so we can investigate the issue.

**Comment by ghost** [comment]
Also, please try using the modified sample attached
[quickblox-react-native-chat-sample.zip](https://github.com/QuickBlox/quickblox-react-native-sdk/files/8171574/quickblox-react-native-chat-sample.zip)
