### ISSUE TITLE
Android push notification payload doesn't have notification body

### ISSUE THREAD

**Issue by maharjanaman** [QuickBlox/quickblox-react-native-sdk#74]
The push notification payload received does not have notification property and hence the notification is **not shown** on the notification center of the Android device.
This is the payload received from QuickBlox dashboard,
```
{
  sentTime: 1705380410287,
  data: { message: 'This is a test notification.' },
  from: '113233849327',
  messageId: '0:1705380410307812%74e7e90ff9fd7ecd',
  ttl: 86400,
  collapseKey: 'event39095462',
}
```
This is the payload received from the firebase console,
```
{
  notification: {
    android: {},
    body: 'This is test notification.',
    title: 'Test Notification',
  },
  sentTime: 1705381363477,
  data: { message: 'This is a test notification.' },
  from: '113233849327',
  messageId: '0:1705381363488080%74e7e90f74e7e90f',
  ttl: 2419200,
  collapseKey: <package_name>,
}
```
Am I missing something here on setup?

**Comment by kirillTolmachev** [comment]
Hello @maharjanaman 
There are 2 types of FCM push messages. Notification and Data messages. 
1. Notification message
The Notification message will be shown automatically when your application is in background mode, when the application is in the foreground you need to handle the message by your hands from a callback. Another one different it's exist an additional object **notification** with fields **body, title**. You can see this object in your log.

2. Data message
The Data message will not be shown automatically, all behavior will be handled by your hands. The additional object **notification** is absent and all values you need to add to the **data** object.

The link to the documentation: https://firebase.google.com/docs/cloud-messaging/concept-options

The problem is a message that you receive from FCM console it's a **notification** message but from QuickBlox you receive the **data** message. The QuickBlox right now supports only **data** messages and the message from QuickBlox won't be shown automatically. You need to add logic to build and show notifications from a library that you using.

**Comment by maharjanaman** [comment]
I'll be closing this now.
